### ISSUE TITLE
win7少api-ms-win-core-path-l1-1-0

### ISSUE THREAD

**Issue by lych2005a** [jiaojiaodubai/sort-jianying-draft#1]
需打包win7版本

**Comment by jiaojiaodubai** [comment]
您好，目前项目只有我一个人在维护，所以回复有点不及时。
据了解，`api-ms-win-core-path-l1-1-0`是Windows 7的系统路径下的文件，你可以参考[这篇知乎帖子](https://zhuanlan.zhihu.com/p/532646405)进行修复。
此外，出现这样的问题可能是因为[Python3.9已经停止对Windows 7的支持](http://www.zkea.net/blog/detail/python-pyinstaller-missing-api-ms-win-core-path-l1-1-0-dll.html)。我会考虑在下一版本中用Python3.8打包以便支持Windows7，敬请关注。

**Comment by jiaojiaodubai** [comment]
> 需打包win7版本

你好，2.7.0版本编译有Win7版，只是暂时没有在github发布，你可通过下方链接获取。
链接:https://pan.baidu.com/s/1rmybACROBazxeLqsovil9g?pwd=v97n
提取码:v97n
