### ISSUE TITLE
Thanks for your project

### ISSUE THREAD

**Issue by NERanger** [jiaojiaodubai/sort-jianying-draft#2]
您好，感谢您的开源项目。我们这边目前有一个项目也需要用到类似的一些技术，想看看能不能找您做一个有偿的技术咨询。如果您对后续合作感兴趣的话，可以联系我：derizhangzsy@gmail.com

**Comment by jiaojiaodubai** [comment]
您好，请在邮件中详细说明。

**Comment by NERanger** [comment]
好的，麻烦请您提供一个联系方式

**Comment by jiaojiaodubai** [comment]
> 好的，麻烦请您提供一个联系方式

jiaojiaodubai23@gmail.com
