### ISSUE TITLE
国际版支持

### ISSUE THREAD

**Issue by forhuan** [jiaojiaodubai/sort-jianying-draft#3]
国际版的路径是CapCut而不是JianyingPro

**Comment by jiaojiaodubai** [comment]
收到，将在下次更新中改进



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月23日(周日) 晚上8:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jiaojiaodubai/sort-jianying-draft] 国际版支持 (Issue #3)




 
国际版的路径是CapCut而不是JianyingPro

**Comment by jiaojiaodubai** [comment]
[新版本](https://github.com/jiaojiaodubai/sort-jianying-draft/releases/tag/2.7.1)已经支持剪映国际版，并且支持同时安装剪映国际版和剪映国内版的用户。
