### ISSUE TITLE
你好请问有办法实现在剪映草稿中配置图片关键帧吗？

### ISSUE THREAD

**Issue by CNDotaBest** [jiaojiaodubai/sort-jianying-draft#4]

**Comment by jiaojiaodubai** [comment]
你是指草稿文件里面那个预览图（`draft_cover.jpg`）吗？

**Comment by CNDotaBest** [comment]
通过修改draft_info.json的keyframes实现图像的上下左右移动。您知道这个功能吗？

**Comment by jiaojiaodubai** [comment]
你或许应该关注`draft_content.json`这个文件

**Comment by CNDotaBest** [comment]
关于draft_content.json有官方资料吗？我现在搞的云里雾里。。。

**Comment by jiaojiaodubai** [comment]
据我所知，没有这样的公开资料。我自己写程序的时候也是连蒙带猜的。

我刚才简单测试了一下，以下内容可能对你有帮助：

```json
/* draft_content.json */
"materials": {
    "videos": [
        {
            "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
            "material_name": "XXX.jpg",
            "path": "C:/.../XXX.jpg",
        },
        
    ]
}
"tracks": [
    /* 这里是轨道i */
    {   
        /* 轨道i上的片段 */
        "segments:" [
            /* 一个剪辑操作 */
            "clip": {
                        // 旋转角度
                        "rotation": 223.0,
                        /* 放大倍数 */
                        "scale": {
                            "x": 1.0,
                            "y": 1.0
                        },
                        "transform": {
                            /* 移动距离（与在程序中填写的值不一样，这里经过了换算） */
                            "x": 0.011979166666666667,
                            "y": 0.0536231884057971
                        }
                    },
            /* 关键帧 */
            "common_keyframes": [
                ...
            ]
            "material_id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
        ]
    },
]
```

因为提问内容与本程序无关，我将关闭这个issue。

**Comment by CNDotaBest** [comment]
感谢您的答复
&nbsp;


该邮件从移动设备发送



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月4日(星期一) 下午5:17
收件人: ***@***.***&gt;; 
抄送: "BuLaiDeLi, ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jiaojiaodubai/sort-jianying-draft] 你好请问有办法实现在剪映草稿中配置图片关键帧吗？ (Issue #4)





 
据我所知，没有这样的公开资料。我自己写程序的时候也是连蒙带猜的。
 
我刚才简单测试了一下，以下内容可能对你有帮助：
 /* draft_content.jso */ "materials": {     "videos": [         {             "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",             "material_name": "XXX.jpg",             "path": "C:/.../XXX.jpg",         },              ] } "tracks": [     /* 这里是轨道i */     {            /* 轨道i上的片段 */         "segments:" [             /* 一个剪辑操作 */             "clip": {                         // 旋转角度                         "rotation": 223.0,                         /* 放大倍数 */                         "scale": {                             "x": 1.0,                             "y": 1.0                         },                         "transform": {                             /* 移动距离（与在程序中填写的值不一样，这里经过了换算） */                             "x": 0.011979166666666667,                             "y": 0.0536231884057971                         }                     },             /* 关键帧 */             "common_keyframes": [                 ...             ]             "material_id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"         ]     }, ]
 
因为提问内容与本程序无关，我将关闭这个issue。
